// Auth
export const SET_USER = 'SET_USER'
export const CLEAR_USER = 'CLEAR_USER'

// Facilities
export const GET_FACILITY_LIST = 'GET_FACILITY_LIST'
export const GET_FACILITY_TYPE_LIST = 'GET_FACILITY_TYPE_LIST'

// commons
export const GET_DISTRICT_LIST = 'GET_DISTRICT_LIST'
export const GET_OWNERSHIP_TYPE_LIST = 'GET_OWNERSHIP_TYPE_LIST'

// Patient Transfers
export const GET_TRANSFER_LIST = 'GET_TRANSFER_LIST'
export const UPDATE_TRANSFER_STATUS = 'UPDATE_TRANSFER_STATUS'
