// Accounts
export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const GET_DISTRICT_LIST = 'GET_DISTRICT_LIST';
export const GET_STATE_LIST = 'GET_STATE_LIST';
export const GET_CITIES_LIST = 'GET_CITIES_LIST';
export const GET_LOCAL_BODY_LIST = 'GET_LOCAL_BODY_LIST';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const USER_TYPE_LIST = 'USER_TYPE_LIST';
export const UPDATE_USER_PROFILE_ERROR = 'UPDATE_USER_PROFILE_ERROR';
export const SET_UPATE_USER_PROFILE_API_STATE = 'SET_UPATE_USER_PROFILE_API_STATE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const GET_PORTEA_USERS = 'GET_PORTEA_USERS';

// Facilities
export const GET_FACILITY_LIST = 'GET_FACILITY_LIST';
export const GET_FACILITY_TYPE_LIST = 'GET_FACILITY_TYPE_LIST';
export const GET_FACILITY_INFRASTRUCTURE_LIST =  'GET_FACILITY_INFRASTRUCTURE_LIST';
export const GET_ROOM_TYPE_LIST =  'GET_ROOM_TYPE_LIST';
export const GET_BED_TYPE_LIST =  'GET_BED_TYPE_LIST';
export const GET_SHORT_FACILITY_LIST = 'GET_SHORT_FACILITY_LIST';
export const GET_FACILITY_STAFF_LIST = 'GET_FACILITY_STAFF_LIST';
export const GET_STAFF_DESIGNATION_LIST = 'GET_STAFF_DESIGNATION_LIST';
export const GET_FACILITY_ADMINSTRATORS_LIST = 'GET_FACILITY_ADMINSTRATORS_LIST';

//inventories
export const GET_FACILITY_INVENTORY_LIST = 'GET_FACILITY_INVENTORY_LIST'
export const GET_INVENTORY_TYPE_LIST = 'GET_INVENTORY_TYPE_LIST'
export const SET_ERROR_CREATE_INVENTORY = 'SET_ERROR_CREATE_INVENTORY'

// commons
export const GET_OWNERSHIP_TYPE_LIST = 'GET_OWNERSHIP_TYPE_LIST';

// Patients
export const GET_PATIENT_LIST = 'GET_PATIENT_LIST';
export const GET_CLINICAL_STATUS_LIST = 'GET_CLINICAL_STATUS_LIST';
export const GET_CLUSTER_GROUP_LIST = 'GET_CLUSTER_GROUP_LIST';
export const SET_CURRENT_PATIENT = 'SET_CURRENT_PATIENT';
export const CLEAR_PATIENT = 'CLEAR_PATIENT';

// Patient Transfers
export const GET_TRANSFER_LIST = 'GET_TRANSFER_LIST';
export const UPDATE_TRANSFER_STATUS = 'UPDATE_TRANSFER_STATUS';
export const UPDATE_TRANSFER_STATUS_ERROR = 'UPDATE_TRANSFER_STATUS_ERROR';
export const GET_COVID_STATUS_LIST = 'GET_COVID_STATUS_LIST';
export const GET_PATIENT_STATUS_LIST = 'GET_PATIENT_STATUS_LIST';
export const SET_TRANSFER_UPDATE_API_STATE = 'SET_TRANSFER_UPDATE_API_STATE';
export const ADD_PATIENT_TRANSFER = 'ADD_PATIENT_TRANSFER'; 
export const ADD_PATIENT_TRANSFER_ERROR = 'ADD_PATIENT_TRANSFER_ERROR';
export const SET_TRANSFER_ADD_API_STATE = 'SET_TRANSFER_ADD_API_STATE';

// Toast
export const CREATE_TOAST_NOTIFICATION = 'CREATE_TOAST_NOTIFICATION';
//testing labs
export const GET_TESTING_LABS_LIST = 'GET_TESTING_LABS_LIST'
